### ISSUE TITLE
data source with excel files

### ISSUE THREAD

**Issue by jonrtaylor** [mbevand/florida-covid19-line-list-data#2]
while importing excel files to pandas is not as clean as using CSV's, these files contain more granular information on the deaths than what you are using. You can account for daily deltas and match the date a death is reported to the date the case was reported and thereby give significantly more accurate estimates. See the second sheet of the excel file mentioned below.

http://ww11.doh.state.fl.us/comm/_partners/covid19_report_archive/

Look for the state_linelist_20200706.xlsx file as an example. Files follow a simple naming format which can be used to download the files programatically. You can also include the tables from the PDF's if you want to analyze the most accurate data possible. Now that I've made you aware of much more accurate data, I anticipate your next update with excitement!

**Comment by mbevand** [comment]
Thanks, I looked through these PDF and Excel files and I determined I can already do everything you explained with the CSV data alone, however it might not be very useful (see last paragraph)

For example this death reported in state_linelist_20200706.pdf:
```
Death County Age Gender Travel_related Travel_detail Contact_with_a_known_case Jurisdiction Date_case_counted
3,709 Wakulla 65 Male No (empty) Yes FL resident 04/01/20
```

...is reported as such in the CSV:
```
        County   Age    Age_group Gender Jurisdiction Travel_related Origin   ...    Died Case_ Contact                   Case1               EventDate               ChartDate ObjectId
10255  Wakulla  65.0  65-74 years   Male  FL resident             No    NaN   ...     Yes   Yes     Yes  2020/04/01 05:00:00+00  2020/03/19 00:00:00+00  2020/04/01 05:00:00+00    10256
```

With both files, we know when the case was reported (4/1), and we can know when the person died using the technique you described (examining daily updates made to the CSV).

The FL DOH websites keeps the last 7 daily line list PDF/Excel files. I already have backups of the last 10 daily CSV files. So there is nothing more I could download to give me more data. All I can do is examine daily deaths since 6/27 (the first day I started making daily backups of the CSV)

**Comment by mbevand** [comment]
Actually I notice the latest `state_linelist_YYYYMMDD.xlsx` files in the tab `Deaths` have a `Newly identified death` column. I could simply read this boolean, instead of examining the daily deltas of death...

**Comment by mbevand** [comment]
In case you care: https://twitter.com/zorinaq/status/1282780503884496898 Blocking me was totally unnecessary.

**Comment by mbevand** [comment]
Actually the Excel files are useless to identify deaths by reading the `Newly identified death` marker. My script `gamma.py` needs the `EventDate` column (date of onset of symptoms, or test, or diagnostic, whichever is earlier) to calculate onset-to-death. But `EventDate` or its equivalent is not in the Excel files. Sad.
